### PR TITLE
Add support for HomeWorks QSX systems

### PR DESCRIPTION
**Pull request by cbw**
- Add support for QSX processors by including their ProjectType string. Tested against QSX processor in HomeAssistant dev environment.
- Add baseline support for Ketra lamps by adding `SpectrumTune` to the `light` section of `_LEAP_DEVICE_TYPES`, and for dimming them by adding `GoToSpectrumTuningLevel` support to `set_value()`.
- Fix a bug where when the color/color temperature of a Ketra lamp changes, the `ColorTuningStatus` message does not contain a `Level` attribute and pylutron-caseta incorrectly assumes that means the zone is off.
- Add support for keypad button LEDs (creates switch devices for each button LED, subscribes to state from processor, and turns LEDs on and off from Home Assistant state changes).
- Add `tap_button` function to send keypad button presses to the processor. This providers the necessary support to add button entities into the `lutron_caseta` Home Assistant component.

### CODE REVIEW

**Comment by danaues** [comment]
@cbw , looks great.  I'll be away until early next week.  I'll plan on merging after doing some tests then.

Thanks!

**Comment by cbw** [comment]
@danaues I'll keep hacking away on it in the meantime. As I got to know the code better, much of what you did for RA3 worked out of the box, but there are some additional HWQSX features I'd like to add as well. Enjoy your time away!

**Comment by cbw** [comment]
Added support for keypad button LEDs – presents them as switches to Home Assistant, subscribes to LED state from the processor, and turns LEDs on and off based on Home Assistant state changes.

**Comment by cbw** [comment]
Added the `tap_button` function to support sending keypad button presses to the Lutron Processor. I have a PR for the  `lutron_caseta` component I'll submit once this gets merged.

**Comment by danaues** [comment]
Hey @cbw 

I haven't forgotten about this.  I'm working on getting my PR into the main pylutron_caseta source.  Having to make some changes to a few things based on the maintainers advice.  As soon as I have that all sorted out, we'll integrate your changes.

**Comment by cbw** [comment]
Sounds good! If if makes sense for me to PR mine against the mainline pylutron_caseta, I can rebase against there once you merge as well

**Comment by cbw** [comment]
Now that your changes are merged, I'll go ahead and rebase against [gurumitts](https://github.com/gurumitts) and PR there

**Comment by danaues** [comment]
@cbw   Sounds great.  It will be great to have both systems supported.

**Pull request closed without merging**
